// src/utils/pdfTemplateGenerator.js

import { jsPDF } from 'jspdf';

export function createPDFTemplate() {
  const doc = new jsPDF();
  
  // Set background color
  doc.setFillColor(240, 240, 240);
  doc.rect(0, 0, 210, 297, 'F');  // A4 size

  // Add title
  doc.setFontSize(24);
  doc.setTextColor(0, 0, 0);
  doc.text('Language Learning Session', 105, 20, { align: 'center' });

  // Add decorative line
  doc.setDrawColor(0, 0, 0);
  doc.setLineWidth(0.5);
  doc.line(20, 25, 190, 25);

  // Add section headers
  const sections = ['Conversation', 'Translation', 'Vocabulary'];
  let yPosition = 40;

  sections.forEach((section, index) => {
    // Add section header
    doc.setFillColor(200, 200, 200);
    doc.rect(20, yPosition, 170, 10, 'F');
    doc.setFontSize(16);
    doc.setTextColor(0, 0, 0);
    doc.text(section, 25, yPosition + 7);

    // Add content area
    doc.setDrawColor(150, 150, 150);
    doc.setLineWidth(0.1);
    doc.rect(20, yPosition + 15, 170, 60);

    // Move to next section
    yPosition += 85;
  });

  // Add footer
  doc.setFontSize(10);
  doc.setTextColor(100, 100, 100);
  doc.text('Generated by Language Learning Assistant', 105, 290, { align: 'center' });

  return doc;
}